version: "3.8"
services:
  ##############################################################################################################
  # Wildlife licencing EPS API service - api service is found on localhost:3000
  ##############################################################################################################
  eps-web:
    image: wildlife-licencing/eps-api:${TAG:-latest}
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # Wildlife licencing EPS WEB service - web service is found on localhost:4000
  ##############################################################################################################
  eps-api:
    image: wildlife-licencing/eps-web:${TAG:-latest}
    ports:
      - "4000:4000"
    env_file:
      - ./env/eps-api.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
