version: "3.8"
name: wls
services:
  ##############################################################################################################
  # Wildlife licencing API service - api service is found on localhost:3000
  ##############################################################################################################
  api:
    image: wildlife-licencing/api:${TAG:-latest}
    ports:
      - "3000:3000"
    env_file:
      - ./env/api.env

  ##############################################################################################################
  # Wildlife licencing API service - The application queue processor
  ##############################################################################################################
#  aqp:
#    image: wildlife-licencing/aqp:${TAG:-latest}
#    env_file:
#      - ./env/aqp.env
#      - ./env/aqp-secrets.env

  ##############################################################################################################
  # Wildlife licencing API service - The application extract processor
  ##############################################################################################################
#  aep:
#    image: wildlife-licencing/aep:${TAG:-latest}
#    env_file:
#      - ./env/aep.env
#      - ./env/aep-secrets.env
#    volumes:
#      - ./resources/cron/application-extract.crontab:/var/spool/cron/crontabs/root:ro

  ##############################################################################################################
  # Wildlife licencing API service - The reference data extract processor - run on a schedule
  ##############################################################################################################
#  rep:
#    image: wildlife-licencing/rep:${TAG:-latest}
#    env_file:
#      - ./env/rep.env
#      - ./env/rep-secrets.env
#    volumes:
#      - ./resources/cron/repdata-extract.crontab:/var/spool/cron/crontabs/root:ro
#    command: crond -f -l 2


  ##############################################################################################################
  # Wildlife licencing API service - The reference data extract processor - run on a schedule
  ##############################################################################################################
#  fqp:
#    image: wildlife-licencing/fqp:${TAG:-latest}
#    env_file:
#      - ./env/fqp.env
#      - ./env/fqp-secrets.env

  ##############################################################################################################
  # Wildlife licencing WLS WEB service - web service is found on localhost:4000
  ##############################################################################################################
  web:
    image: wildlife-licencing/web:${TAG:-latest}
    ports:
      - "4000:4000"
    env_file:
      - ./env/web.env
    volumes:
      - scandir:/scandir
      - certs:/certs


volumes:
  scandir:
  certs:
