version: "3.8"
services:
  ##############################################################################################################
  # Wildlife licencing EPS API service
  ##############################################################################################################
  eps-web:
    image: wildlife-licencing/eps-api:${TAG:-latest}
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # Wildlife licencing EPS WEB service
  ##############################################################################################################
  eps-api:
    image: wildlife-licencing/eps-web:${TAG:-latest}
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure