version: "3.8"
services:
#######################################################
# nginx
#######################################################
  nginx:
    image: wls_nginx
    ports:
      - "80:8080"
    deploy:
      restart_policy:
        condition: on-failure
