version: "3.8"
services:
#######################################################
# nginx
#######################################################
  nginx:
    image: wls_nginx
    ports:
      - "80:8080"
      - "443:4443"
#    command: ["tail", "-f", "/dev/null"]
    deploy:
      restart_policy:
        condition: on-failure
