# See https://github.com/SonarSource/sonarcloud-github-action
on:
  # Trigger the analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: npm ci
      - name: Run lint check
        run: npm run lint
      # As per https://jestjs.io/docs/troubleshooting we can improve performance in CI by getting the number of CPU
      # cores we have available and passing that number to jest
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v2
      - name: Run tests
        run: npm run test -- -max-workers ${{ steps.cpu-cores.outputs.count }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
