name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  


jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Lerna
      run: npm install --global lerna@6
    - name: Bootstrap dependencies
      run: lerna bootstrap

  lint:
    name: Lint
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Cached Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Run Lint
      run: npm run lint

  commit-lint:
    runs-on: ubuntu-latest
    needs: install_dependencies
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Cached Node Modules
        uses: actions/cache@v2
        with:
         path: '**/node_modules'
         key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Conventional Commit Linting
        run: npx commitlint --from=HEAD~1 --to=HEAD
        continue-on-error: true

  test:
    name: Test
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Cached Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Run Tests
      run: npm run test
  
  sonar: 
      name: SonarCloud Scan
      needs: install_dependencies
      runs-on: ubuntu-latest
      steps:
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}