name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          # Disabling shallow clone is recommended for improving relevancy of reporting
#          fetch-depth: 0
#      - name: Install node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '16.13.0'
#      - name: Install dependencies
#        run: npm ci
#      - name: Run lint check
#        run: npm run lint
#      - name: Run tests
#        run: npm run test
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker-base-build-publish:
    #    needs: [build]
    #    if: github.ref == 'refs/heads/feat/build-and-publish-to-ecr-github-actions'
    uses: DEFRA/wildlife-licencing/.github/workflows/docker-build-and-push-jobs.yaml
    with:
      CONTEXT: 'packages/web-service'
      DOCKER_FILE: 'packages/web-service/Dockerfile.prod'
    secrets: inherit
