name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  


jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Bootstrap dependencies
      run: |
        ls
        npm ci
        ls

  lint:
    name: Lint
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Cached Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Run Lint
      run: npm run lint

  commit-lint:
    runs-on: ubuntu-latest
    needs: install_dependencies
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Cached Node Modules
        uses: actions/cache@v2
        with:
         path: '**/node_modules'
         key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Conventional Commit Linting
        run: npx commitlint --from=HEAD~1 --to=HEAD
        continue-on-error: true

  test:
    name: Test
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Cached Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Run Tests
      run: npm run test

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: coverage/
  
  sonar: 
      name: SonarCloud Scan
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage/
      - name: check
        run: ls
      - name: Sonar Cloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}