on:
  workflow_call:
    inputs:
      CONTEXT:
        required: true
        type: string
      DOCKER_FILE:
          required: true
          type: string

jobs:
  docker-base-build-publish:
    name: Push Base Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '16.13.0'

      - name: Build base and builder
        run: npm run docker:build-base

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
#          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
#          ECR_REPOSITORY: new_front_office
          IMAGE_TAG: test_github_actions
#          REPOSITORY: my-ecr-repo
        run: |
          docker build -t built_image --file ${{ inputs.DOCKER_FILE }} ${{ inputs.CONTEXT }}
          docker tag built_image ${{ steps.login-ecr.outputs.registry }}/natural_england_wildlife/new_front_office:${IMAGE_TAG}
          docker push ${{ steps.login-ecr.outputs.registry }}/natural_england_wildlife/new_front_office:${IMAGE_TAG}



